stages:
  - build_and_test
  - deploy

build_and_test:
  image: rust
  stage: build_and_test
  only:
    - merge_requests
    - master
  cache:
    key: build_test-${CI_RUNNER_EXECUTABLE_ARCH}
    paths:
      - .yarn
  script:
    - apt update -y && apt install -y curl libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
    - apt install -y nodejs && npm install -g yarn
    - cd app && yarn install
    - yarn run test && yarn run build
    - cd ..
    - cargo test --release && cargo build --release
    - cd e2e && yarn install
    - env "DATABASE_URL=sqlite::memory:" ../target/release/simple-log-book &
    - env CYPRESS_BASE_URL=http://localhost:4000 yarn run ci

push:
  stage: deploy
  dependencies:
    - build_and_test
  only:
    - master
  tags:
    - shell
  script:
    - podman login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - podman build -t $CI_REGISTRY_IMAGE:latest .
    - podman push $CI_REGISTRY_IMAGE:latest