stages:
  - test
  - deploy

test_frontend:
  image: node:14
  stage: test
  cache:
    key: yarn-${CI_RUNNER_EXECUTABLE_ARCH}
    paths:
      - .yarn
  script:
    - cd app
    - yarn install --cache-folder .yarn
    - yarn run test
  only:
    - merge_requests
    - master

test_backend:
  image: rust
  stage: test
  cache:
    key: rust-${CI_RUNNER_EXECUTABLE_ARCH}
    paths:
      - .rust
  script:
    - cargo test --target-dir=.rust --verbose
  only:
    - merge_requests
    - master

push:
  image: docker:stable
  services:
    - docker:dind
  stage: deploy
  dependencies:
    - test_frontend
    - test_backend
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest