[package]
name = "simple-log-book"
version = "0.1.0"
authors = ["fanchao <dev@fanchao.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0"
async-std = { version = "1", features = ["attributes"] }
sqlx = { version = "0", features = ["sqlite", "chrono", "decimal", "runtime-async-std-native-tls", "json"]}
serde = "1"
serde_derive = "1"
serde_json = "1"
tide = "0"
anyhow = "1"
itertools = "0"